### ISSUE TITLE
IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by ckalpit** [AlexandreKempf/automacdoc#3]
command: `automacdoc . ./../wiki`

Traceback (most recent call last):
  File ".../env/bin/automacdoc", line 11, in <module>
    sys.exit(main())
  File ".../env/lib/python3.6/site-packages/automacdoc/main.py", line 11, in main
    write_doc(argv[1], argv[2])
  File ".../env/lib/python3.6/site-packages/automacdoc/automacdoc.py", line 324, in write_doc
    write_module(root_path, module_name, mdfile_path)
  File ".../env/lib/python3.6/site-packages/automacdoc/automacdoc.py", line 211, in write_module
    for n, o in inspect.getmembers(module, inspect.isclass)
  File ".../env/lib/python3.6/site-packages/automacdoc/automacdoc.py", line 211, in <listcomp>
    for n, o in inspect.getmembers(module, inspect.isclass)
  File ".../env/lib/python3.6/site-packages/automacdoc/automacdoc.py", line 93, in create_class
    clas["source"] = rm_docstring_from_source(inspect.getsource(obj))
  File ".../env/lib/python3.6/site-packages/automacdoc/automacdoc.py", line 20, in rm_docstring_from_source
    del source[1]  # remove docstring
IndexError: list assignment index out of range

**Comment by TrangPham** [comment]
I got this error as well

**Comment by AlexandreKempf** [comment]
The project is not very well maintain because I have very little time for it unfortunaly :( 
But I guess the bug arises when you don't have a docstring on a function !

**Comment by CaioTeixeira95** [comment]
Hello guys! @AlexandreKempf i just fixed it in my PR, you just need to push it to pipy, because the version of the code there is not the same of GitHub.

**Comment by priti-aid** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @kimyc3825, @kaymal, @aeastmead, @Sheg5, @Brian0906, @kckustomac, @tylercb, @dakotagrusak, @atoder, @SVAtanasov, @nitinnkdz, @vigneshmrajendran, @workluckti, @doctorx, @Hazel512, @powerddt, @kuppu, @PD130102, @xartisan, @GiovanniStephens
